[package]
name = "dhcp-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dhcproto = "0.7.0"
icmp = "0.3.0"
pnet = "0.31"
pnet_datalink = "0.31"
etherparse = "0.10.1"
packet = "0.1.4"
